variables:
  AUDIT_AWS_ELB_ALERT_LIST:
    description: alert list for generating notifications
    required: true
    type: array
    default:
      - elb-old-ssl-policy
      - elb-inventory
      - elb-current-ssl-policy
  AUDIT_AWS_ELB_ALERT_RECIPIENT:
    description: email recipient for notification
    required: true
    type: string
    default:
  AUDIT_AWS_ELB_ALERT_NO_OWNER_RECIPIENT:
    description: email recipient for objects with no owner tag if owner tag is enabled
    required: true
    type: string
    default:
  AUDIT_AWS_ELB_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: true
  AUDIT_AWS_ELB_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "always"
  AUDIT_AWS_ELB_OWNER_TAG:
    description: AWS tag whose value is an email address specifying the owner of the ELB object
    required: false
    type: string
    default: "OWNER"
  AUDIT_AWS_ELB_FULL_JSON_REPORT:
    description: notify or nothing
    required: true
    type: string
    default: "notify"
  AUDIT_AWS_ELB_OWNERS_HTML_REPORT:
    description: notify or nothing
    required: true
    type: string
    default: "notify"  
  AUDIT_AWS_ELB_ROLLUP_REPORT:
    description: notify or nothing
    required: true
    type: string
    default: "notify"  
  AUDIT_AWS_ELB_DEBUG_REPORT:
    description: notify or nothing
    required: true
    type: string
    default: "notify"  
  AUDIT_AWS_ELB_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
#        - us-west-1
#        - us-west-2
#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
#       - eu-west-1
#       - sa-east-1
